### ISSUE TITLE
`ncipollo/release-action` triggers `Error 403: Resource not accessible by integration`

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/csv-parser#6]
See https://github.com/sebastianbergmann/csv-parser/actions/runs/8222218102/job/22483452456.

**Comment by sebastianbergmann** [comment]
@localheinz I copy/paste-d what we implemented for PHPUnit to here. What am I missing? Thanks!

**Comment by localheinz** [comment]
@sebastianbergmann 

Perhaps related to 

- https://github.com/ncipollo/release-action/issues/208
- https://docs.github.com/en/rest/using-the-rest-api/troubleshooting-the-rest-api?apiVersion=2022-11-28#resource-not-accessible

Can you check and compare

- https://github.com/sebastianbergmann/csv-parser/settings/actions
- https://github.com/sebastianbergmann/phpunit/settings/actions

?

![CleanShot 2024-03-10 at 17 34 19@2x](https://github.com/sebastianbergmann/csv-parser/assets/605483/46a72ac5-bde8-43bd-9b7e-2e44043784c1)

Alternatively, maybe #7 helps?

**Comment by sebastianbergmann** [comment]
For `sebastianbergmann/phpunit` I already had `Actions > General > Workflow permissions > Read and write permissions`.
